import { useMemo } from 'react';

export function LineChart({ data, color = '#2a8a7a', height = 190, fill = true }: { data: number[]; color?: string; height?: number; fill?: boolean }) {
  const { points, area } = useMemo(() => { const min = Math.min(...data) - 3; const max = Math.max(...data) + 3; const coords = data.map((v, i) => `${(i / (data.length - 1)) * 100},${height - ((v - min) / (max - min)) * (height - 20) - 10}`); return { points: coords.join(' '), area: `0,${height} ${coords.join(' ')} 100,${height}` }; }, [data, height]);
  return <svg viewBox={`0 0 100 ${height}`} preserveAspectRatio="none" className="h-full w-full overflow-visible"><defs><linearGradient id="chart-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity=".17" /><stop offset="100%" stopColor={color} stopOpacity="0" /></linearGradient></defs>{[25, 75, 125, 175].map((y) => <line key={y} x1="0" x2="100" y1={y} y2={y} stroke="#e2e8f0" strokeWidth=".35" />)}{fill && <polygon points={area} fill="url(#chart-fill)" />}<polyline points={points} fill="none" stroke={color} strokeWidth="1.5" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

export function Sparkline({ data, color = '#2a8a7a' }: { data: number[]; color?: string }) { return <div className="h-8 w-24"><LineChart data={data} color={color} height={40} fill={false} /></div>; }

export function Donut({ value, color = '#2a8a7a', size = 120, label }: { value: number; color?: string; size?: number; label?: string }) { const r = 42; const circumference = 2 * Math.PI * r; return <div className="relative" style={{ width: size, height: size }}><svg viewBox="0 0 100 100" className="h-full w-full -rotate-90"><circle cx="50" cy="50" r={r} fill="none" stroke="#f1f5f9" strokeWidth="10" /><circle cx="50" cy="50" r={r} fill="none" stroke={color} strokeWidth="10" strokeLinecap="round" strokeDasharray={`${(value / 100) * circumference} ${circumference}`} /></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-xl font-bold text-slate-900">{value}%</span>{label && <span className="text-[9px] text-slate-400">{label}</span>}</div></div>; }

export function MiniBars({ values, color = '#2a8a7a' }: { values: number[]; color?: string }) { return <div className="flex h-8 items-end gap-1">{values.map((v, i) => <div key={i} className="w-1.5 rounded-t-sm opacity-80" style={{ height: `${v}%`, background: color }} />)}</div>; }

export function HorizontalBarChart({ items }: { items: { label: string; value: number; color?: string }[] }) { return <div className="space-y-4">{items.map((item) => <div key={item.label}><div className="mb-1.5 flex justify-between text-xs"><span className="text-slate-600">{item.label}</span><span className="font-bold tabular-nums text-slate-800">{item.value}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full transition-all duration-700" style={{ width: `${item.value}%`, background: item.color ?? '#2a8a7a' }} /></div></div>)}</div>; }
